/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(rename = "instance")]
    pub instance: String,
}

impl ApiError {
    pub fn new(r#type: String, title: String, detail: String, instance: String) -> ApiError {
        ApiError {
            r#type,
            title,
            status: None,
            detail,
            instance,
        }
    }
}

