/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiError : RFC 7807 compliant problem details object representing an API error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiError {
    /// A URI reference identifying the problem type.
    #[serde(rename = "type")]
    pub r#type: String,
    /// A short, human-readable summary of the problem type.
    #[serde(rename = "title")]
    pub title: String,
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    #[serde(rename = "status")]
    pub status: i32,
    /// A human-readable explanation specific to this occurrence of the problem.
    #[serde(rename = "detail")]
    pub detail: String,
    /// A URI reference identifying the specific occurrence of the problem.
    #[serde(rename = "instance")]
    pub instance: String,
}

impl ApiError {
    /// RFC 7807 compliant problem details object representing an API error.
    pub fn new(r#type: String, title: String, status: i32, detail: String, instance: String) -> ApiError {
        ApiError {
            r#type,
            title,
            status,
            detail,
            instance,
        }
    }
}

