/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrichmentCollectionStatusResponse {
    /// Status represents the processing state of a bulk enrichment job.
    #[serde(rename = "status")]
    pub status: Status,
}

impl EnrichmentCollectionStatusResponse {
    pub fn new(status: Status) -> EnrichmentCollectionStatusResponse {
        EnrichmentCollectionStatusResponse {
            status,
        }
    }
}
/// Status represents the processing state of a bulk enrichment job.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "READY")]
    Ready,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "PENDING")]
    Pending,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ready
    }
}

