/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrichTransactionCollectionResponse {
    /// ID is the work ID for the enrichment request.
    #[serde(rename = "id")]
    pub id: String,
    /// Link is the URL to the downloadable tar.gz results archive.
    #[serde(rename = "link")]
    pub link: String,
}

impl EnrichTransactionCollectionResponse {
    pub fn new(id: String, link: String) -> EnrichTransactionCollectionResponse {
        EnrichTransactionCollectionResponse {
            id,
            link,
        }
    }
}

