/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrichTransactionsRequestInner {
    /// Content is the payment description, maximum 128 characters.
    #[serde(rename = "content")]
    pub content: String,
    /// CountryCode is the ISO 3166-1 alpha-2 two-character country code.
    #[serde(rename = "countryCode")]
    pub country_code: String,
}

impl EnrichTransactionsRequestInner {
    pub fn new(content: String, country_code: String) -> EnrichTransactionsRequestInner {
        EnrichTransactionsRequestInner {
            content,
            country_code,
        }
    }
}

