/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrichmentResponse {
    /// Merchant is the name of the merchant.
    #[serde(rename = "merchant")]
    pub merchant: String,
    /// Description is a brief description of the merchant.
    #[serde(rename = "description")]
    pub description: String,
    /// Categories lists categories fitting the description of the merchant.
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
    /// Logo is a base64-encoded PNG or JPEG representing the merchant logo.
    #[serde(rename = "logo")]
    pub logo: String,
    /// Location describes the country and city. May be empty if the API returns null.
    #[serde(rename = "location")]
    pub location: String,
    /// Address describes the exact address of purchase. May be empty if the API returns null.
    #[serde(rename = "address")]
    pub address: String,
}

impl EnrichmentResponse {
    pub fn new(merchant: String, description: String, categories: Vec<String>, logo: String, location: String, address: String) -> EnrichmentResponse {
        EnrichmentResponse {
            merchant,
            description,
            categories,
            logo,
            location,
            address,
        }
    }
}

