/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : Standard error response envelope containing a list of RFC 7807 problem details errors.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// List of problem details errors returned by the API.
    #[serde(rename = "errors")]
    pub errors: Vec<models::ApiError>,
}

impl ErrorResponse {
    /// Standard error response envelope containing a list of RFC 7807 problem details errors.
    pub fn new(errors: Vec<models::ApiError>) -> ErrorResponse {
        ErrorResponse {
            errors,
        }
    }
}

