/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "errors")]
    pub errors: Vec<models::ApiError>,
}

impl ErrorResponse {
    pub fn new(errors: Vec<models::ApiError>) -> ErrorResponse {
        ErrorResponse {
            errors,
        }
    }
}

